- CHANGELOG.md
- package.json
- translations/ui-marc-authorities/en.json
Add permissions to View and Edit marc authorities records
[UIMARCAUTH-5](https://issues.folio.org/browse/UIMARCAUTH-5)
> UIMARCAUTH-5 Add Edit MARC authority record permission

- jest.config.js
- mocks/authorities.json
- src/components/index.js
- src/components/search-results-list/index.js
- src/components/search-results-list/search-results-list.js
- src/components/search-results-list/search-results-test.test.js
- src/constants/shapes/authority-shape.js
- src/constants/shapes/index.js
- src/routes/search.js
- translations/ui-marc-authorities/en.json
Add `<SearchResultsList>` component that displays list of MARC authority records
[UIMARCAUTH-18](https://issues.folio.org/browse/UIMARCAUTH-18)
> UIMARCAUTH-18: Display Results List

- CHANGELOG.md
- src/constants/filterConfig.js
- src/views/AuthoritiesSearch/AuthoritiesSearch.js
- src/views/AuthoritiesSearch/AuthoritiesSearch.test.js
- translations/ui-marc-authorities/en.json
Display a Date Created filter.
Issue: [UIMARCAUTH-14](https://issues.folio.org/browse/UIMARCAUTH-14)
> UIMARCAUTH-14 Display a Date Created filter

- CHANGELOG.md
- src/components/SearchTextareaField/SearchTextareaField.js
- src/components/SearchTextareaField/SearchTextareaField.test.js
- src/views/AuthoritiesSearch/AuthoritiesSearch.js
https://issues.folio.org/browse/UIMARCAUTH-32
> UIMARCAUTH-32: Search box - Hit enter key must run search

- CHANGELOG.md
- src/components/SearchResultsList/SearchResultsList.js
Do not bold Auth/Ref in Authorized/Reference column
[UIMARCAUTH-50](https://issues.folio.org/browse/UIMARCAUTH-50
> UIMARCAUTH-50:Do not bold Auth/Ref in Authorized/Reference colum

- CHANGELOG.md
- src/components/FilterNavigation/FilterNavigation.js
- src/components/FilterNavigation/FilterNavigation.test.js
- src/components/FilterNavigation/index.js
- src/components/SearchFilters/SearchFilters.js
- src/components/SearchFilters/SearchFilters.test.js
- src/components/SearchTextareaField/SearchTextareaField.js
- src/components/index.js
- src/constants/index.js
- src/constants/navigationSegments.js
- src/constants/rawSearchableIndexes.js
- src/views/AuthoritiesSearch/AuthoritiesSearch.js
- src/views/AuthoritiesSearch/AuthoritiesSearch.test.js
- translations/ui-marc-authorities/en.json
Display Browse headings toggle.
[UIMARCAUTH-28](https://issues.folio.org/browse/UIMARCAUTH-28)
> UIMARCAUTH-28: Browse MARC Authority Records > Display Browse headings toggle

- CHANGELOG.md
- src/constants/rawSearchableIndexes.js
- src/queries/useAuthorities/useAuthorities.test.js
- src/queries/utils/buildQuery.js
- src/queries/utils/buildQuery.test.js
- src/views/AuthoritiesSearch/AuthoritiesSearch.js
Update Keyword Search query to apply Exclude see also filter selection.
[UIMARCAUTH-52](https://issues.folio.org/browse/UIMARCAUTH-52)
> UIMARCAUTH-52: Update Keyword Search query to apply Exclude see also filter selection

- CHANGELOG.md
- package.json
Need to increment package version so reference envs use the latest code
> Increment package version after pre-release

- package.json
https://github.com/folio-org/ui-quick-marc/pull/279
> Increment quickMARC dep version to 5.0.0

- CONTRIBUTING.md
- package.json
to pass TCR interfaces are required
> TCR-12 add missing interfaces/permissions + code of conduct

- CHANGELOG.md
- src/constants/browseHeadingTypesMap.js
- src/constants/headingTypesValues.js
- src/constants/index.js
- src/queries/useAuthoritiesBrowse/useAuthoritiesBrowse.js
- src/queries/utils/buildHeadingTypeQuery.js
- src/queries/utils/buildHeadingTypeQuery.test.js
- src/queries/utils/index.js
https://issues.folio.org/browse/UIMARCAUTH-89
**GET /browse/authorities** doesn't treat `headingType` as query parameter, so it requires to pass `headingType` value into `query` param. [API Docs](https://s3.amazonaws.com/foliodocs/api/mod-search/s/mod-search.html#operation/browseAuthorities)
> UIMARCAUTH-89 Browse option selection searches all

- CHANGELOG.md
- src/queries/useAuthority.js
https://issues.folio.org/browse/UIMARCAUTH-97
load authority lines by chunks as some records can have > 100 lines
> UIMARCAUTH-97 The selected Heading/Reference value does not match the value highlighted in the detail record.

- src/queries/useAuthority.js
https://issues.folio.org/browse/UIMARCAUTH-97
> UIMARCAUTH-97 fix useAuthority to handle not matched authority

- CHANGELOG.md
- translations/ui-marc-authorities/en.json
https://issues.folio.org/browse/UIMARCAUTH-92
> UIMARCAUTH-92  Labels update

- CHANGELOG.md
- src/components/AuthoritiesSearchForm/AuthoritiesSearchForm.js
- src/constants/rawSearchableIndexes.js
- src/constants/searchableIndexesValues.js
- src/context/AuthoritiesSearchContext.js
- src/index.js
- src/queries/useAuthoritiesBrowse/useAuthoritiesBrowse.test.js
- translations/ui-marc-authorities/en.json
Change Browse option default selection label and behavior.
[UIMARCAUTH-86](https://issues.folio.org/browse/UIMARCAUTH-86)
> UIMARCAUTH-86: Change Browse option default selection label and behavior

- CHANGELOG.md
- package.json
> Release v1.0.4

- CHANGELOG.md
- src/hooks/useSortColumnManager/useSortColumnManager.js
- src/routes/SearchRoute/SearchRoute.js
- src/views/AuthoritiesSearch/AuthoritiesSearch.js
Issue: https://issues.folio.org/browse/UIMARCAUTH-135
The search result list doesn't sort by clicking on the title of column
> Search result list gets sorted by clikcing on the title of the column.

- package.json
Issue: [FE: update outdated dependencies](https://issues.folio.org/browse/FOLIO-3477)
FE: update outdated dependencies
Could not revert pr#147 as there were changes ahead of merging it.
Hence reverting few changes of earlier pr https://github.com/folio-org/ui-myprofile/pull/185, moving back those dependencies that were moved from "devDependencies" to "dependencies"
> FOLIO-3477 : FE: update outdated dependencies

- CHANGELOG.md
- src/queries/useAuthoritiesBrowse/useAuthoritiesBrowse.js
- src/queries/useAuthoritiesBrowse/useAuthoritiesBrowse.test.js
Change request param headingTypeExt to isTitleHeadingRef
https://user-images.githubusercontent.com/19309423/169785730-50801913-bf4f-4bd2-bd4b-5dc5a946365a.mp4
[UIMARCAUTH-151](https://issues.folio.org/browse/UIMARCAUTH-151)
> UIMARCAUTH-151: Change request param headingTypeExt to isTitleHeadingRef

- package.json
- src/views/AuthoritiesSearch/AuthoritiesSearch.js
Issue: https://issues.folio.org/browse/UIMARCAUTH-130
Add a Select all/Un-select all checkbox on Results List
> UIMARCAUTH-130: Add a Select all/Un-select all on Results List

- CHANGELOG.md
- package.json
Issue:  FE: update outdated dependencies
https://issues.folio.org/browse/UIMARCAUTH-145
1. Observed several linking warnings when "yarn install" command is issued.
2. Added the associated libraries to devDependencies inpackage.json file to remove the linking warnings.
The below linking warnings still exist.
The versions of the packages "react-flexbox-grid, react-highlight-words, react-quill@1.3.5, react-tether and @apollo/client" in "stripes-components" and  the version of "graphql" in stripes-core are resulting in these warnings.
These have to be handled as part of the associated ticket and beyond the scope of this ticket.
> UIMARCAUTH-145: FE: update outdated dependencies

- src/constants/searchableIndexesMap.js
Fix parameters for Name title search option, addition to https://github.com/folio-org/ui-marc-authorities/pull/149
[UIMARCAUTH-143](https://issues.folio.org/browse/UIMARCAUTH-143)
> UIMARCAUTH-143 Fix search parameters for Name title

- CHANGELOG.md
- src/constants/queryKeys.js
- src/queries/useAuthority.js
- src/queries/useMarcSource.js
- src/routes/AuthorityViewRoute/AuthorityViewRoute.js
- src/routes/AuthorityViewRoute/AuthorityViewRoute.test.js
- src/views/AuthorityView/AuthorityView.js
- src/views/AuthorityView/AuthorityView.test.js
- translations/ui-marc-authorities/en.json
Fix an error appearing when opening already deleted MARC Authority record.
Added a catch block which redirects to marc authorities search list if there's an error while getting a source record.
[UIMARCAUTH-152](https://issues.folio.org/browse/UIMARCAUTH-152)
> UIMARCAUTH-152: An error appears when user tries to close the editing window of already deleted "MARC Authority" record

- CHANGELOG.md
- src/routes/SearchRoute/SearchRoute.test.js
- src/views/AuthoritiesSearch/AuthoritiesSearch.js
Hide record counter in pane subtitle when Browsing records
[UIMARCAUTH-169](https://issues.folio.org/browse/UIMARCAUTH-169)
> UIMARCAUTH-169 Hide counters when browsing records

- CHANGELOG.md
- src/views/AuthoritiesSearch/AuthoritiesSearch.js
- src/views/AuthoritiesSearch/AuthoritiesSearch.test.js
See [pull request](https://github.com/folio-org/ui-plugin-find-authority/pull/26)
> UIMARCAUTH-182: Add the Expand the Search & filter pane option

- CHANGELOG.md
- package.json
Add permissions to get Authority Source filter options
[UIMARCAUTH-187](https://issues.folio.org/browse/UIMARCAUTH-187)
> UIMARCAUTH-187 Add permissions for Authourity Source filter

- CHANGELOG.md
- mocks/authorities.json
- src/views/AuthoritiesSearch/AuthoritiesSearch.js
- src/views/AuthoritiesSearch/AuthoritiesSearch.test.js
- translations/ui-marc-authorities/en.json
Display number of titles for linked Authority records
[UIMARCAUTH-177](https://issues.folio.org/browse/UIMARCAUTH-177)
> UIMARCAUTH-177 MARC authority: Search Results/Browse List: Add a new column Number of titles

- CHANGELOG.md
- src/views/AuthoritiesSearch/AuthoritiesSearch.js
- src/views/AuthoritiesSearch/AuthoritiesSearch.test.js
Fix constant re-rendering after doing a search with one result.
And prevent the Detail View pane from automatically opening after it is closed.
[UIMARCAUTH-204](https://issues.folio.org/browse/UIMARCAUTH-204)
[UIPFAUTH-37](https://github.com/folio-org/ui-plugin-find-authority/pull/45)
[UISAUTCOMP-30](https://github.com/folio-org/stripes-authority-components/pull/44)
https://user-images.githubusercontent.com/77053927/203529222-514799f7-692e-4d2c-b35d-4a36bd589103.mp4
> UIMARCAUTH-204: Error appears when the user executes search in "MARC Authority" app

- CHANGELOG.md
- src/constants/index.js
- src/constants/searchResultsListColumns.js
- src/hooks/useSortColumnManager/useSortColumnManager.test.js
- src/routes/SearchRoute/SearchRoute.js
- src/views/AuthoritiesSearch/AuthoritiesSearch.js
- src/views/AuthoritiesSearch/AuthoritiesSearch.test.js
Make the number of titles a link. Clicking this link should open the Inventory app with the bib records linked with that authority record.
[UIMARCAUTH-180](https://issues.folio.org/browse/UIMARCAUTH-180)
https://user-images.githubusercontent.com/77053927/204369825-90fdb537-39e0-4f06-be6c-36cd3387bf20.mp4
> UIMARCAUTH-180: MARC authority app: Results List: Number of titles column > Link each number to return all bib records linked to the authority record 

- src/views/AuthorityView/AuthorityView.js
- src/views/AuthorityView/AuthorityView.test.js
Cover scenarios described in this [comment](https://issues.folio.org/browse/UIMARCAUTH-178?focusedCommentId=152869&page=com.atlassian.jira.plugin.system.issuetabpanels%3Acomment-tabpanel#comment-152869):
- If the authority record is linked to bib records AND the Authorized/Reference value = Authorized then the delete confirmation modal indicates it is linked to bib records **as expected** 
- If the authority record is linked to bib records AND the Authorized/Reference value = Reference then the delete confirmation modal DOES not indicate that the record is linked to bib records. IT should display the same modal as №1 if the authority record it is on is linked to a bib record. 
- If the authority record is linked to bib records AND the Authorized/Reference value = Auth/Ref then the delete …
> UIMARCAUTH-178: MARC authority: Delete MARC authority record handling

- CHANGELOG.md
- package.json
Bump quick-marc to 6.0.0
[UIMARCAUTH-226](https://issues.folio.org/browse/UIMARCAUTH-226)
> UIMARCAUTH-226: Bump quick-marc to 6.0.0

- src/views/AuthoritiesSearch/ReportsModal/ReportsModal.js
- src/views/AuthoritiesSearch/ReportsModal/ReportsModal.test.js
- translations/ui-marc-authorities/en.json
Check the date format.
[UIMARCAUTH-208](https://issues.folio.org/browse/UIMARCAUTH-208)
https://user-images.githubusercontent.com/77053927/216951057-795b00bb-bdec-433d-a1de-1148766a843f.mp4
> UIMARCAUTH-208: Add date format check

- src/views/AuthoritiesSearch/ReportsModal/ReportsModal.js
> UIMARCAUTH-208: Fix stripesFinalForm import path

- CHANGELOG.md
- package.json
- src/views/AuthorityView/AuthorityView.js
- src/views/AuthorityView/AuthorityView.test.js
- translations/ui-marc-authorities/en.json
As a librarian, I want the ability to print my source record so that I can review any changes. 
[UIMARCAUTH-233](https://issues.folio.org/browse/UIMARCAUTH-233)
Added the print button
https://user-images.githubusercontent.com/124583895/218995895-565139db-fff0-47a8-972d-bb8fb4ddba18.mov
> UIMARCAUTH-233: MARC Authority | Print Source record

- CHANGELOG.md
- src/views/AuthorityView/AuthorityView.js
Set the correct title in print popup
[UIMARCAUTH-235](https://issues.folio.org/browse/UIMARCAUTH-235)
https://user-images.githubusercontent.com/124583895/219965739-7bc53ccb-42bb-4dcd-837f-f84d70262510.mov
> UIMARCAUTH-235: Change the print popup title with new requirements

- CHANGELOG.md
- src/views/AuthoritiesSearch/AuthoritiesSearch.test.js
- src/views/AuthoritiesSearch/ReportsMenu/ReportsMenu.js
- src/views/AuthoritiesSearch/ReportsMenu/ReportsMenu.test.js
Remove `Failed updates reports` option for the Orchid release.
[UIMARCAUTH-231](https://issues.folio.org/browse/UIMARCAUTH-231)
> UIMARCAUTH-231: Remove 'Failed updates reports' option for the Orchid release.

- src/routes/AuthorityViewRoute/AuthorityViewRoute.test.js
- src/views/AuthorityView/AuthorityView.test.js
- test/jest/__mock__/stripesCore.mock.js
> UIMARCAUTH-261: Fix tests

- CHANGELOG.md
- src/views/AuthorityView/AuthorityView.js
Add icons alongside action buttons.
[UIMARCAUTH-239](https://issues.folio.org/browse/UIMARCAUTH-239)
> UIMARCAUTH-239: Detail Record Actions dropdown menu > Add icons to the left of each action

- CHANGELOG.md
- test/jest/helpers/harness.js
https://issues.folio.org/browse/UIMARCAUTH-253
> UIMARCAUTH-253: Avoid private paths in stripes-core import

- CHANGELOG.md
- src/routes/BrowseRoute/BrowseRoute.js
Browse catalog. Trim space at begining and end of query string
[UIMARCAUTH-251](https://issues.folio.org/browse/UIMARCAUTH-251)
> UIMARCAUTH-251

- CHANGELOG.md
- src/views/AuthoritiesSearch/AuthoritiesSearch.js
- src/views/AuthoritiesSearch/ReportsMenu/ReportsMenu.js
- translations/ui-marc-authorities/en.json
https://user-images.githubusercontent.com/19309423/231761361-84553ddf-8cf7-4e3c-a74e-349b7c194a2a.mp4
[UIMARCAUTH-212](https://issues.folio.org/browse/UIMARCAUTH-212)
> UIMARCAUTH-212 Global Headings Report | UX | Failed updates: linked bibliographic fields (CSV) (real-time)

- CHANGELOG.md
- package.json
Upgrade the records-editor.records interface.
[UIMARCAUTH-272](https://issues.folio.org/browse/UIMARCAUTH-272)
> UIMARCAUTH-272: Upgrade the records-editor.records interface.

- CHANGELOG.md
- src/hooks/useSortColumnManager/useSortColumnManager.js
- src/hooks/useSortColumnManager/useSortColumnManager.test.js
- src/index.js
- src/routes/BrowseRoute/BrowseRoute.js
- src/routes/SearchRoute/SearchRoute.js
- src/views/AuthoritiesSearch/AuthoritiesSearch.js
- src/views/AuthoritiesSearch/AuthoritiesSearch.test.js
- test/jest/helpers/harness.js
Retain Search and Browse search terms.
[UIMARCAUTH-264](https://issues.folio.org/browse/UIMARCAUTH-264)
[stripes-authority-components/pull/82](https://github.com/folio-org/stripes-authority-components/pull/82)
[ui-plugin-find-authority/pull/66](https://github.com/folio-org/ui-plugin-find-authority/pull/66)
https://github.com/folio-org/ui-marc-authorities/assets/77053927/b6b6372d-54d3-468d-bcf9-74ba27ecbf10
> UIMARCAUTH-264: Retain Search and Browse search terms.

- CHANGELOG.md
- package.json
https://issues.folio.org/browse/UIMARCAUTH-288
When importing MARC Authority through the data import module a user cannot see JSON details for Authority.
- Added  "inventory-storage.authorities.collection.get" to the "MARC Authority: View MARC authority record" permission set
> UIMARCAUTH-288: Add permission to "MARC Authority: View MARC authority record"

- CHANGELOG.md
- src/views/AuthorityView/AuthorityView.js
Required changes in markHighlightedFields releated with UISAUTCOMP-59
[UIMARCAUTH-291](https://issues.folio.org/browse/UIMARCAUTH-291)
> UIMARCAUTH-291 - updated markHighlightedFields releated with UISAUTCOMP-59

- package.json
> UIMARCAUTH-300: Bump 'quick-marc' and 'stripes-acq-components'.

- CHANGELOG.md
- src/utils.js
- src/views/AuthorityView/AuthorityView.js
Add `Local` or `Shared` to flag MARC authorities.
https://github.com/folio-org/ui-quick-marc/pull/578
https://github.com/folio-org/ui-plugin-find-authority/pull/72
https://github.com/folio-org/stripes-authority-components/pull/94
[UIMARCAUTH-268](https://issues.folio.org/browse/UIMARCAUTH-268)
> UIMARCAUTH-268: Add 'Local' or 'Shared' to flag MARC authorities.

- .github/workflows/build-npm-release.yml
- .github/workflows/build-npm.yml
- CHANGELOG.md
- package.json
- test/jest/__mock__/stripesCore.mock.js
Update Node.js to v18 in GitHub Actions.
[UIMARCAUTH-302](https://issues.folio.org/browse/UIMARCAUTH-302)
> UIMARCAUTH-302: Update Node.js to v18 in GitHub Actions.

- CHANGELOG.md
- package.json
Add persmission 'link suggestions' to authority view.
https://issues.folio.org/browse/UIPFAUTH-76?focusedCommentId=181235&page=com.atlassian.jira.plugin.system.issuetabpanels%3Acomment-tabpanel#comment-181235
> UIMARCAUTH-317: Add persmission 'link suggestions' to authority view.

- CHANGELOG.md
- src/queries/useAuthoritiesDelete/useAuthorityDelete.js
- src/queries/useAuthoritiesDelete/useAuthorityDelete.test.js
- src/views/AuthorityView/AuthorityView.js
- src/views/AuthorityView/AuthorityView.test.js
Delete Shared MARC authority record.
https://github.com/folio-org/stripes-authority-components/pull/104
[UIMARCAUTH-284](https://issues.folio.org/browse/UIMARCAUTH-284)
https://github.com/folio-org/ui-marc-authorities/assets/77053927/72e704fe-dab8-4bcf-9035-54780e603134
> UIMARCAUTH-284: Delete Shared MARC authority record.

- CHANGELOG.md
- src/routes/AuthorityViewRoute/AuthorityViewRoute.js
- src/routes/AuthorityViewRoute/AuthorityViewRoute.test.js
- src/views/AuthorityView/AuthorityView.js
Load MARC Authority source file with correct tenantId
https://github.com/folio-org/ui-marc-authorities/assets/19309423/15200768-5925-4f12-b2fe-6524cdc9b912
[UIMARCAUTH-313](https://issues.folio.org/browse/UIMARCAUTH-313)
> UIMARCAUTH-313 Load MARC Authority source file with correct tenantId

- package.json
> UIMARCAUTH-284: Add permission to see central tenant perms.

- CHANGELOG.md
- src/views/AuthorityView/AuthorityView.js
Edit Shared MARC authority record, update Shared & Local Instances
[UIMARCAUTH-285](https://issues.folio.org/browse/UIMARCAUTH-285)
https://github.com/folio-org/ui-quick-marc/pull/590
> UIMARCAUTH-285 Edit Shared MARC authority record, update Shared & Local Instances

- CHANGELOG.md
- src/routes/BrowseRoute/BrowseRoute.js
- src/views/AuthoritiesSearch/AuthoritiesSearch.js
Remove unnecessary `pagingOffset` prop.
[UIPFAUTH-81](https://issues.folio.org/browse/UIPFAUTH-81)
https://github.com/folio-org/ui-plugin-find-authority/pull/79
https://github.com/folio-org/stripes-authority-components/pull/111
https://github.com/folio-org/stripes-components/pull/2126
> UIMARCAUTH-327: Remove unnecessary pagingOffset prop.

- CHANGELOG.md
- package.json
Hide permission `MARC Authority: Create new MARC authority record`
[UIMARCAUTH-314](https://issues.folio.org/browse/UIMARCAUTH-314)
> UIMARCAUTH-314: Hide permission 'MARC Authority: Create new MARC authority record'

- src/queries/index.js
- src/queries/useAuthorityLinksCount/index.js
- src/queries/useAuthorityLinksCount/useAuthorityLinksCount.js
- src/queries/useAuthorityLinksCount/useAuthorityLinksCount.test.js
- src/views/AuthorityView/AuthorityView.js
- src/views/AuthorityView/AuthorityView.test.js
Display the correct number of links during the removal of a marc authority record.
[UIMARCAUTH-284](https://issues.folio.org/browse/UIMARCAUTH-284)
https://github.com/folio-org/ui-marc-authorities/assets/77053927/ea322bf1-67af-4a27-8307-5d80351600d0
> UIMARCAUTH-284: Number of links must not be taken from another tenant.

- src/routes/AuthorityViewRoute/AuthorityViewRoute.js
- src/routes/AuthorityViewRoute/AuthorityViewRoute.test.js
- src/views/AuthorityView/AuthorityView.js
- src/views/AuthorityView/AuthorityView.test.js
Display the correct number of linked bib records in the modal window that opens after clicking on the Delete MARC authority action.
[UIMARCAUTH-284](https://issues.folio.org/browse/UIMARCAUTH-284)
https://github.com/folio-org/ui-marc-authorities/assets/77053927/41898421-04b0-4b8a-aefd-06b94861e79d
> UIMARCAUTH-284: Display the correct number of linked bib records.

- CHANGELOG.md
- package.json
Remove eslint deps that are already listed in eslint-config-stripes.
[UIMARCAUTH-304](https://issues.folio.org/browse/UIMARCAUTH-304)
> UIMARCAUTH-304: Remove eslint deps that are already listed in eslint-config-stripes.

- CHANGELOG.md
- translations/ui-marc-authorities/en.json
Change create MARC authority action label
[UIMARCAUTH-352](https://issues.folio.org/browse/UIMARCAUTH-352)
> UIMARCAUTH-352 Change create MARC authority action label

- CHANGELOG.md
- src/queries/useAuthoritiesDelete/useAuthorityDelete.js
Change API URL to delete MARC authority record.
[UIMARCAUTH-340](https://issues.folio.org/browse/UIMARCAUTH-340)
https://github.com/folio-org/ui-marc-authorities/assets/77053927/2ac84936-01cb-4c03-93ce-79dcfe793b07
> UIMARCAUTH-340: Change API URL to delete MARC authority record.

- CHANGELOG.md
- package.json
- translations/ui-marc-authorities/en.json
Added permissions for viewing and editing/creating/deleting Authority Source files in Settings
[UIMARCAUTH-344](https://issues.folio.org/browse/UIMARCAUTH-344)
> UIMARCAUTH-344 Added permissions for viewing and editing/creating/deleting Authority Source files in Settings

- src/views/AuthoritiesSearch/AuthoritiesSearch.js
Remove the horizontal scroll for the result list.
[UIMARCAUTH-343](https://issues.folio.org/browse/UIMARCAUTH-343?focusedCommentId=194211&page=com.atlassian.jira.plugin.system.issuetabpanels%3Acomment-tabpanel#comment-194211)
> UIMARCAUTH-343: Remove the horizontal scroll for the result list.

- package.json
Align [permission](https://github.com/folio-org/mod-entities-links/blob/fdb0ecdf69db71f3b031bc2170f248de2129725d/descriptors/ModuleDescriptor-template.json#L220) with the delete authority API.
This is the follow-up to this https://github.com/folio-org/ui-marc-authorities/pull/336
[UIMARCAUTH-340](https://issues.folio.org/browse/UIMARCAUTH-340)
> UIMARCAUTH-340: Align permission with the delete authority API.

- CHANGELOG.md
- src/views/AuthoritiesSearch/AuthoritiesSearch.js
Add Search type dropdown to Advanced search modal.
[UIMARCAUTH-295](https://issues.folio.org/browse/UIMARCAUTH-295)
https://github.com/folio-org/stripes-authority-components/pull/132
https://github.com/folio-org/ui-marc-authorities/assets/77053927/ee3854fd-db44-4c4d-ad05-3c700ded43ab
> UIMARCAUTH-295: Add Search type dropdown to Advanced search modal.

- CHANGELOG.md
- src/settings/ManageAuthoritySourceFiles/ManageAuthoritySourceFiles.js
- src/settings/ManageAuthoritySourceFiles/ManageAuthoritySourceFiles.test.js
- src/settings/ManageAuthoritySourceFiles/getValidators.js
- src/settings/ManageAuthoritySourceFiles/getValidators.test.js
- translations/ui-marc-authorities/en.json
Implement creation of Authority Source files
https://github.com/folio-org/ui-marc-authorities/assets/19309423/d8002f9f-3c26-4631-b44d-a62b488240e5
https://github.com/folio-org/ui-marc-authorities/assets/19309423/84266327-5e07-43a1-a56e-1f0e6e5d2a00
[UIMARCAUTH-360](https://issues.folio.org/browse/UIMARCAUTH-360)
https://github.com/folio-org/stripes-smart-components/pull/1426
> UIMARCAUTH-360 Implement creation of Authority Source files

- CHANGELOG.md
- package.json
Add the same permissions that are listed in `quickMARC: Create a new MARC authority record` to `Create new MARC authority record`.
https://github.com/folio-org/ui-quick-marc/pull/651
[UIMARCAUTH-382](https://issues.folio.org/browse/UIMARCAUTH-382)
> UIMARCAUTH-382: Add the same permissions that are listed in `quickMARC: Create a new MARC authority record` to `Create new MARC authority record`.

- src/settings/ManageAuthoritySourceFiles/ManageAuthoritySourceFiles.js
- src/settings/ManageAuthoritySourceFiles/getFieldComponents.js
- src/settings/ManageAuthoritySourceFiles/getValidators.js
- src/settings/ManageAuthoritySourceFiles/useManageAuthoritySourceFiles.js
- src/settings/ManageAuthoritySourceFiles/useManageAuthoritySourceFiles.test.js
Fixed validation of Source Files settings
https://github.com/folio-org/ui-marc-authorities/assets/19309423/cd4d87b9-28a3-4612-878b-9a9767d9565e
https://github.com/folio-org/ui-marc-authorities/assets/19309423/fd790de6-3a25-40f7-9113-90ec35f96a8e
[UIMARCAUTH-359](https://folio-org.atlassian.net/browse/UIMARCAUTH-359)
> UIMARCAUTH-359 Fix validation when editing

- CHANGELOG.md
- src/settings/ManageAuthoritySourceFiles/getValidators.js
- src/settings/ManageAuthoritySourceFiles/getValidators.test.js
- translations/ui-marc-authorities/en.json
Validate if the authority file name is unique for authority file settings.
[UIMARCAUTH-377](https://folio-org.atlassian.net/browse/UIMARCAUTH-377)
https://github.com/folio-org/ui-marc-authorities/assets/77053927/22891f05-22c3-4720-a6a7-2664bc4974e9
> UIMARCAUTH-377: Validate if the authority file name is unique for authority file settings.

- src/settings/ManageAuthoritySourceFiles/getValidators.js
- src/settings/ManageAuthoritySourceFiles/getValidators.test.js
- translations/ui-marc-authorities/en.json
Follow-up PR.
Validate if there is a whitespace in the base url for authority file settings.
[UIMARCAUTH-370](https://folio-org.atlassian.net/browse/UIMARCAUTH-370)
https://github.com/folio-org/ui-marc-authorities/assets/77053927/ffbabee6-1dcf-46fe-bcd4-5cbc19fadd46
> UIMARCAUTH-370: Validate if there is a whitespace in the base url for authority file settings.

- CHANGELOG.md
- src/routes/BrowseRoute/BrowseRoute.js
- src/routes/SearchRoute/SearchRoute.js
- translations/ui-marc-authorities/en.json
MARC Authority app > Search and Browse Results > Update HTML page title with search term entered
[UIMARCAUTH-371](https://folio-org.atlassian.net/browse/UIMARCAUTH-371)
> UIMARCAUTH-371 MARC Authority app > Search and Browse Results > Update HTML page title with search term entered

- CHANGELOG.md
- src/settings/ManageAuthoritySourceFiles/ManageAuthoritySourceFiles.js
- src/settings/ManageAuthoritySourceFiles/ManageAuthoritySourceFiles.test.js
Display a generic error message during authority file creation if validation is missing.
https://folio-org.atlassian.net/browse/UIMARCAUTH-405
https://github.com/folio-org/ui-marc-authorities/assets/77053927/88e1f03a-fd5b-4b01-93ea-f2c890a9f2ec
> UIMARCAUTH-405: Display a generic error message during authority file creation if validation is missing.

- CHANGELOG.md
- src/hooks/index.js
- src/hooks/useAuthorityExport/index.js
- src/hooks/useAuthorityExport/useAuthorityExport.js
- src/hooks/useAuthorityExport/useAuthorityExport.test.js
- src/queries/index.js
- src/queries/useAuthorityExport/index.js
- src/queries/useQuickExport/index.js
- src/queries/useQuickExport/useQuickExport.js
- src/queries/useQuickExport/useQuickExport.test.js
- src/views/AuthoritiesSearch/AuthoritiesSearch.js
- src/views/AuthoritiesSearch/AuthoritiesSearch.test.js
- src/views/AuthorityView/AuthorityView.js
- src/views/AuthorityView/AuthorityView.test.js
- translations/ui-marc-authorities/en.json
Quick export from authority detail view
https://github.com/folio-org/ui-marc-authorities/assets/19309423/0877f226-31b6-4054-b995-9329675a0e38
[UIMARCAUTH-375](https://folio-org.atlassian.net/browse/UIMARCAUTH-375)
> UIMARCAUTH-375 Quick export from authority detail view

- CHANGELOG.md
- src/constants/index.js
- src/constants/sortableColumns.js
- src/hooks/useSortColumnManager/useSortColumnManager.test.js
- src/routes/SearchRoute/SearchRoute.js
- src/views/AuthoritiesSearch/AuthoritiesSearch.js
- src/views/AuthoritiesSearch/AuthoritiesSearch.test.js
Pass `showSortIndicator` prop to `SearchResultsList` to display sort indicator in the results header.
https://github.com/folio-org/stripes-components/pull/2333
https://github.com/folio-org/stripes-authority-components/pull/161
[UIMARCAUTH-423](https://folio-org.atlassian.net/browse/UIMARCAUTH-423)
https://github.com/user-attachments/assets/12212e48-e4e9-4ab8-937a-50105c518336
> UIMARCAUTH-423: Pass `showSortIndicator` prop to `SearchResultsList` to display sort indicator in the results header.

- CHANGELOG.md
- package.json
upgrade `marc-records-editor` to 6.0
[UIMARCAUTH-428](https://folio-org.atlassian.net/browse/UIMARCAUTH-428)
> UIMARCAUTH-428 upgrade `marc-records-editor` to 6.0

- src/views/AuthorityView/AuthorityView.css
- src/views/AuthorityView/AuthorityView.js
added a right margin to actions button
[UIMARCAUTH-445](https://folio-org.atlassian.net/browse/UIMARCAUTH-445)
> UIMARCAUTH-445 added a right margin to actions button (follow-up)

- .eslintrc
- CHANGELOG.md
- src/components/AuthorityTitleManager/AuthorityTitleManager.js
- src/components/DateRangeFieldset/DateRangeFieldset.js
- src/components/KeyShortCutsWrapper/KeyShortCutsWrapper.js
- src/index.js
- src/views/AuthoritiesSearch/AuthoritiesSearch.js
- src/views/AuthoritiesSearch/ReportsModal/ReportsModal.js
React v19: refactor away from default props for functional components
[UIMARCAUTH-409](https://folio-org.atlassian.net/browse/UIMARCAUTH-409)
> UIMARCAUTH-409 React v19: refactor away from default props for functional components

- CHANGELOG.md
- package.json
> UIMARCAUTH-461: Upgrade `browse` to `2.0`

- CHANGELOG.md
- package.json
- src/views/AuthorityView/AuthorityView.js
- src/views/AuthorityView/AuthorityView.test.js
Show forth pane with a record history.
https://github.com/folio-org/stripes-marc-components/pull/41
[UIMARCAUTH-465](https://folio-org.atlassian.net/browse/UIMARCAUTH-465)
> UIMARCAUTH-465: Add MarcVersionHistory to display all versions in the fourth pane.

- CHANGELOG.md
- src/queries/useAuditSettings/useAuditSettings.js
- src/views/AuthorityView/AuthorityView.js
- src/views/AuthorityView/AuthorityView.test.js
Display the history feature toggle/icon only if it is enabled in settings. The shared record should call for settings with the central tenant id, local record with the local tenant id.
https://folio-org.atlassian.net/browse/UIMARCAUTH-463
https://github.com/user-attachments/assets/59b54a83-635a-4b24-8fa9-5b2f9b0e3061
> UIMARCAUTH-463: `AuthorityView` - add `tenantId` to `useAuditSettings`.

- CHANGELOG.md
- package.json
- src/queries/useAuditSettings/useAuditSettings.js
- src/views/AuthorityView/AuthorityView.js
- src/views/AuthorityView/AuthorityView.test.js
- retrieve a shared record history from central tenant, a local record history from member tenant;
- disable actions in the 3rd pane when 4th pane is open;
- add permission to view history pane with only with permission "MARC Authority: View MARC authority record".
https://github.com/folio-org/stripes-components/pull/2440
https://github.com/folio-org/stripes-marc-components/pull/44
https://folio-org.atlassian.net/browse/UIMARCAUTH-465
> UIMARCAUTH-465: Pass `tenantId` to `MarcVersionHistory`, disable actions, add permission (follow-up).

- package.json
https://folio-org.atlassian.net/browse/UIMARCAUTH-465?focusedCommentId=255240
https://folio-org.atlassian.net/browse/UIMARCAUTH-465?focusedCommentId=255240
> UIMARCAUTH-465: Add `audit.config.groups.settings.audit.authority.collection.get` to `MARC Authority: View MARC authority record`.

- CHANGELOG.md
- package.json
- src/hooks/useReportGenerator/useReportGenerator.js
- src/hooks/useReportGenerator/useReportGenerator.test.js
- src/views/AuthoritiesSearch/ReportsModal/ReportsModal.js
replace moment with day.js
[UIMARCAUTH-462](https://folio-org.atlassian.net/browse/UIMARCAUTH-462)
> UIMARCAUTH-462 replace moment with day.js

- CHANGELOG.md
- package.json
Display users in version history panel with the `MARC Authority: View MARC authority record` permission.
https://folio-org.atlassian.net/browse/UIMARCAUTH-476
> UIMARCAUTH-476: Add the permission `users.collection.get` to `MARC Authority: View MARC authority record`.
