- CHANGELOG.md
- package.json
- src/components/SearchResultsList/SearchResultsList.js
- src/components/SearchResultsList/SearchResultsList.test.js
- src/constants/index.js
- src/constants/searchResultsListColumns.js
- src/views/AuthoritiesSearch/AuthoritiesSearch.js
- src/views/AuthoritiesSearch/AuthoritiesSearch.test.js
- Add Action button on results pane.
- Add checkboxes with visibility status of `SearchResultsList` columns
- Add tests
- add `lodash` package
Issue: [UIMARCAUTH-20](https://issues.folio.org/browse/UIMARCAUTH-20)
We could test child component's props as html attributes, but for objects or arrays in props we should check them as strings.
```
jest.mock('../../components', () => ({
...jest.requireActual('../../components'),
SearchResultsList: (props) => {
const mapedProps = mockMapValues(props, (prop) => (typeof prop === 'object') ? JSON.stringify(prop) : prop);
return <div data-testid='SearchResultsList' {...mapedProps} />;
},
}));
...
describe('when click on "Type of Heading" checkbox', () => {
it('should hide "Type of Heading" column', () => {
const { getByTestId } = …
```
> UIMARCAUTH-20: Implement Results List Column Chooser

- CHANGELOG.md
- src/components/SearchResultsList/SearchResultsList.js
Fix Results List column headers are smushed when third pane is opened.
The approach was chosen based on the [readme.md](https://github.com/folio-org/stripes-components/blob/master/lib/MultiColumnList/readme.md) for MultiColumnList where it is said:
> Prefer pixel `px` values to percent values. <...> percents `%` are less practical and often result columns being overly squeezed
[UIMARCAUTH-40](https://issues.folio.org/browse/UIMARCAUTH-40)
> UIMARCAUTH-40: Fix Results List column headers are smushed

- CHANGELOG.md
- src/constants/rawSearchableIndexes.js
- src/constants/searchableIndexesMap.js
- src/constants/searchableIndexesValues.js
- translations/ui-marc-authorities/en.json
Remove Authority UUID search option from the Search Options dropdown.
Issue: [UIMARCAUTH-34](https://issues.folio.org/browse/UIMARCAUTH-34)
> UIMARCAUTH-34: Search Options dropdown: Remove Authority UUID search option

- CHANGELOG.md
- src/components/MultiSelectionFacet/MultiSelectionFacet.js
- src/components/SearchFilters/SearchFilters.js
- src/views/AuthorityView/AuthorityView.js
-  Change `headingRef` to `headingType`
- update translations 
- add separator to type of heading accordion
Issue: [UIMARCAUTH-36](https://issues.folio.org/browse/UIMARCAUTH-36)
> UIMARCAUTH-36: Update second line heading on QuickMarc view pane

- CHANGELOG.md
- src/constants/searchableIndexesMap.js
- src/constants/searchableIndexesValues.js
- src/queries/utils/buildQuery.js
- src/queries/utils/buildQuery.test.js
- src/views/AuthoritiesSearch/AuthoritiesSearch.test.js
Fix name of `Identifiers (all)` search option. Fix error when url contains invalid search index name
[UIMARCAUTH-46](https://issues.folio.org/browse/UIMARCAUTH-46)
> UIMARCAUTH-46: Cannot get Authority record search - Identifiers search option to work

- CHANGELOG.md
- src/components/SearchResultsList/SearchResultsList.js
- src/components/SearchResultsList/SearchResultsList.test.js
- src/views/AuthoritiesSearch/AuthoritiesSearch.js
- src/views/AuthorityView/AuthorityView.js
Fix closing third pane does not resize the second pane size and Reset all does not reset results list pane.
Changes is `ui-quick-marc` module were needed: [related PR](https://github.com/folio-org/ui-quick-marc/pull/255).
[UIMARCAUTH-37](https://issues.folio.org/browse/UIMARCAUTH-37)
Related: [UIQM-195](https://issues.folio.org/browse/UIQM-195)
> UIMARCAUTH-37: Fix Closing third pane does not resize the second pane

- CHANGELOG.md
- src/queries/utils/buildQuery.js
- src/queries/utils/buildQuery.test.js
Extend request by searching by subjectHeadings = b when user selects Children's subject headings search option.
Issue: [UIMARCAUTH-48](https://issues.folio.org/browse/UIMARCAUTH-48)
> UIMARCAUTH-48: Extend request by searching by subjectHeadings = b when user selects Children's subject headings search option

- CHANGELOG.md
- package.json
Added access requires permission: search.facets.collection.get. 
[UIMARCAUTH-58](https://issues.folio.org/browse/UIMARCAUTH-58)
> UIMARCAUTH-58: Request for Facets fails - missing permissions

- CHANGELOG.md
- src/queries/useAuthorities/useAuthorities.js
- src/queries/useAuthorities/useAuthorities.test.js
- src/queries/utils/buildQuery.js
- src/queries/utils/buildQuery.test.js
Fix cannot search by identifiers that contain a space.
[UIMARCAUTH-57](https://issues.folio.org/browse/UIMARCAUTH-57)
> UIMARCAUTH-57: Cannot search by identifiers that contain a space

- CHANGELOG.md
- translations/ui-marc-authorities/en.json
Renamed the Accordion label and facet label from Subject heading/thesaurus to Thesaurus
Changed "search.subjectHeadings" property inside translations/en.json file
[UIMARCAUTH-112](https://issues.folio.org/browse/UIMARCAUTH-112)
> UIMARCAUTH-112 Rename Subject heading/thesaurus facet to Thesaurus facet

- CHANGELOG.md
- src/components/SearchResultsList/SearchResultsList.js
- src/components/SearchResultsList/SearchResultsList.test.js
- src/views/AuthoritiesSearch/AuthoritiesSearch.js
If there is only one search result, we are displaying the detail record without letting user click on the result.
SearchResultList component is getting totalResults and authorities(results) as props, I have used a useEffect hook which is checking if the totalResults property is one, it will automatically take the result and open it. This is done by pushing the user to a url formed by formatAuthorityRecordLink function in the same component.
https://user-images.githubusercontent.com/101391438/160613018-b23c0af1-934c-4d17-9070-f262c30f72e1.mp4
[UIMARCAUTH-111](https://issues.folio.org/browse/UIMARCAUTH-111
> "UIMARCAUTH-111: If only one result is returned then automatically display detail record"

- CHANGELOG.md
- package.json
- translations/ui-marc-authorities/en.json
Permission: Delete MARC authority record 
Added Delete MARC authority permission inside package.json file with permission name “ui-marc-authorities.authority-record.delete” and display name “Delete MARC authority record”. Also added the translation inside en.json file.
[UIMARCAUTH-67](https://issues.folio.org/browse/UIMARCAUTH-67)
> UIMARCAUTH-67 Permission: Delete MARC authority record.

- CHANGELOG.md
- src/views/AuthorityView/AuthorityView.js
- src/views/AuthorityView/AuthorityView.test.js
The only direct descendants of a `<Paneset>` should be `<Pane>`
components. Here, an extraneous `<div>` wrapper was inserted for the
purpose of providing a test hook. This change resolves the issue by
hooking directly onto the `test-id` of the inner `<Pane>`. This feels a
little risky since that `test-id` is not directly controlled by this
application.
A more thorough fix might be to allow the test-id in `@folio/quick-marc`
to be overridden by prop.
Refs [UIMARCAUTH-122](https://issues.folio.org/browse/UIMARCAUTH-122)
Attn: @JohnC-80, @BogdanDenis (since I don't have write permission here and thus cannot add reviewers)
> UIMARCAUTH-122 correctly scroll the details pane

- CHANGELOG.md
- src/constants/deleteMarcAuthority.js
- src/constants/index.js
- src/queries/useAuthoritiesDelete/useAuthorityDelete.js
- src/queries/useAuthoritiesDelete/useAuthorityDelete.test.js
Modify MARC authority processing for delete.
**Note:** Getting status after deleting MARC Authority record is not working properly now, so this functionality will be rechecked once that bug with getting status is resolved.
[UIMARCAUTH-137](https://issues.folio.org/browse/UIMARCAUTH-137)
> UIMARCAUTH-137: Modify MARC authority processing for delete

- CHANGELOG.md
- package.json
To fix export ".csv" file failed because of missing permission
Extended _subPermissions_ of "MARC Authority: View MARC authority record" with "data-export.quick.export.post" permission.
[UIMARCAUTH-146](https://issues.folio.org/browse/UIMARCAUTH-146)
> UIMARCAUTH-146: Export .csv file failed because of missing permission

- CHANGELOG.md
- src/queries/useAuthoritiesDelete/useAuthorityDelete.js
- src/queries/useAuthoritiesDelete/useAuthorityDelete.test.js
Deleted "MARC Authority" records displayed in result list. 
Increased delete request time delay from 0.5s to 1.5s
[UIMARCAUTH-144](https://issues.folio.org/browse/UIMARCAUTH-144)
> UIMARCAUTH-144: increased time delay to 1.5s

- src/routes/AuthorityQuickMarcEditRoute/AuthorityQuickMarcEditRoute.js
Pass authority record path to quickMARC, which fixes latest version link
https://user-images.githubusercontent.com/19309423/169529676-e72ddb92-9bb6-494c-aaa9-3fe722586cb3.mp4
[UIMARCAUTH-132](https://issues.folio.org/browse/UIMARCAUTH-132)
> UIMARCAUTH-132 Apply to MARC Authority:  Optimistic locking: display error message to inform user about OL

- CHANGELOG.md
- package.json
- src/components/SearchResultsList/SearchResultsList.js
- src/queries/useAuthoritiesBrowse/useAuthoritiesBrowse.js
- src/routes/BrowseRoute/BrowseRoute.js
- src/views/AuthoritiesSearch/AuthoritiesSearch.js
Override default MCL prev and next button disabling
https://user-images.githubusercontent.com/19309423/169289374-3efee374-49f4-4bbe-8e15-cce053605e0f.mp4
https://github.com/folio-org/stripes-components/pull/1800
[UIMARCAUTH-140](https://issues.folio.org/browse/UIMARCAUTH-140)
> UIMARCAUTH-140 [Browse] The page without results is displayed when user go to the last page of result list.

- src/queries/useAuthoritiesDelete/useAuthorityDelete.js
Await for status to be defined to fix multiple requests when querying for status after deleted MARC Authority record.
Fix for [this PR](https://github.com/folio-org/ui-marc-authorities/pull/151)
Now we have one preflight request to `/record-editor/records/status?actionId=<id>` and one GET request:
[UIMARCAUTH-137](https://issues.folio.org/browse/UIMARCAUTH-137)
> UIMARCAUTH-137: Fix multiple requests when querying for status after delete

- .github/workflows/build-npm-release.yml
- .github/workflows/build-npm.yml
- CHANGELOG.md
- src/views/AuthoritiesSearch/AuthoritiesSearch.js
https://issues.folio.org/browse/UIMARCAUTH-147
Only use `history.push` if the pathname and search params have changed.
This is currently causing an issue with lazy loading https://issues.folio.org/browse/STRWEB-30 we want to turn on for all ui modules via stripes.
> UIMARCAUTH-147: Fix history push to support code splitting

- .github/workflows/build-npm-release.yml
- CHANGELOG.md
- package.json
Update NodeJS to v16 in GitHub Actions.
[UIMARCAUTH-149](https://issues.folio.org/browse/UIMARCAUTH-149)
> UIMARCAUTH-149: Update NodeJS to v16 in GitHub Actions

- CHANGELOG.md
- src/hooks/useSortColumnManager/useSortColumnManager.js
- src/hooks/useSortColumnManager/useSortColumnManager.test.js
- src/routes/SearchRoute/SearchRoute.js
Added correct initial sort parameters values inside `useSortColumnManager`
https://user-images.githubusercontent.com/19309423/181725955-addcff54-9a11-41a6-a41d-bce387759ee0.mp4
[UIMARCAUTH-163](https://issues.folio.org/browse/UIMARCAUTH-163)
> UIMARCAUTH-163: The row with "Heading/reference" value doesn't highlight at result list after editing matched tags value more than 1 time

- CHANGELOG.md
- src/components/Filters/BrowseFilters/BrowseFilters.js
- src/components/Filters/ReferencesFilter/ReferencesFilter.js
- src/components/Filters/ReferencesFilter/ReferencesFilter.test.js
- src/components/Filters/SearchFilters/SearchFilters.js
- src/constants/references.js
Remove `Exclude see from also` option from `References` filter in Browse mode
https://user-images.githubusercontent.com/19309423/182143180-0faf7742-bfc2-449f-b432-0391133fffed.mp4
[UIMARCAUTH-162](https://issues.folio.org/browse/UIMARCAUTH-162)
> UIMARCAUTH-162 Browse authority | Remove checkbox 'Exclude see from also' from 'Reference' accordion.

- CHANGELOG.md
- src/views/AuthoritiesSearch/AuthoritiesSearch.js
- src/views/AuthoritiesSearch/AuthoritiesSearch.test.js
- test/jest/__mock__/index.js
- test/jest/__mock__/reactVirtializedAutoSizer.mock.js
- translations/ui-marc-authorities/en.json
Move row selection functionality from `stripes-authority-components` 
https://user-images.githubusercontent.com/19309423/189884191-2cc8ca5d-1f89-49ea-a6a4-4ec7e28a896d.mp4
[UIMARCAUTH-183](https://issues.folio.org/browse/UIMARCAUTH-183)
https://github.com/folio-org/stripes-authority-components/pull/24
https://github.com/folio-org/ui-plugin-find-authority/pull/28
> UIMARCAUTH-183 Results List : Click Link icon/button to select a MARC authority record

- CHANGELOG.md
- src/views/AuthoritiesSearch/AuthoritiesSearch.js
Display selected records counter in pane header
https://user-images.githubusercontent.com/19309423/192479653-c03d343c-2196-40a6-be9e-f42b36bbcb91.mp4
[UIMARCAUTH-186](https://issues.folio.org/browse/UIMARCAUTH-186)
> UIMARCAUTH-186 Browse | The counter of selected records for export doesn't display at pane header

- CHANGELOG.md
- src/views/AuthoritiesSearch/AuthoritiesSearch.js
Remove filters from url when clicking "Reset all"
https://user-images.githubusercontent.com/19309423/196977840-60537202-ade2-4ccc-bcca-af1bb54b1cb3.mp4
https://github.com/folio-org/stripes-authority-components/pull/35
[UIMARCAUTH-191](https://issues.folio.org/browse/UIMARCAUTH-191)
> UIMARCAUTH-191 MARC authority app: Authority source/Thesaurus Facet option does not display value when zero results are returned

- CHANGELOG.md
- package.json
Missing permission for request "/links/authorities/bulk/count". Added it to "MARC Authority: Edit MARC authority record" permission in ui-matc-authorities/package.json
Will be posted soon
[UIMARCAUTH-222](https://issues.folio.org/browse/UIMARCAUTH-222)
> UIMARCAUTH-222: Missing permission for Marc Authority edit

- CHANGELOG.md
- package.json
Reverts folio-org/ui-marc-authorities#226  until back-end interface has been updated
> Revert "UIMARCAUTH-221 Align the module with API breaking change"

- src/views/AuthoritiesSearch/AuthoritiesSearch.test.js
- src/views/AuthoritiesSearch/Reports/Reports.js
- translations/ui-marc-authorities/en.json
Remove button 'Blind authority headings (CSV)'
[UIMARCAUTH-220](https://issues.folio.org/browse/UIMARCAUTH-220?focusedCommentId=155456&page=com.atlassian.jira.plugin.system.issuetabpanels%3Acomment-tabpanel#comment-155456)
> UIMARCAUTH-220: Remove button 'Blind authority headings (CSV)'

- CHANGELOG.md
- src/queries/useExportReport/useExportReport.js
Fix missing payload attribute for export authority headings updates
[UIMARCAUTH-234](https://issues.folio.org/browse/UIMARCAUTH-234)
> UIMARCAUTH-234 Fix incorrect payload structure for Authorities updates export.

- CHANGELOG.md
- package.json
This package no longer causes node version conflicts and so no longer needs to be pinned.
Refs [UIMARCAUTH-236](https://issues.folio.org/browse/UIMARCAUTH-236)
> UIMARCAUTH-236 unpin @vue/compiler-sfc

- CHANGELOG.md
- src/queries/useExportReport/useExportReport.js
- translations/ui-marc-authorities/en.json
Added `description` and `outputFormat` to authority headings updates reports request
[UIMARCAUTH-240](https://issues.folio.org/browse/UIMARCAUTH-240)
> UIMARCAUTH-240  Incorrect "Job type",  "Output type", "Description" for headings updates report export job

- CHANGELOG.md
- package.json
- src/views/AuthoritiesSearch/ReportsModal/ReportsModal.test.js
Added `stripes-authority-components` to `stripesDeps` so translations can be included in bundle
[UIMARCAUTH-260](https://issues.folio.org/browse/UIMARCAUTH-260)
> UIMARCAUTH-260 Added stripes-authority-components to stripesDeps.

- CHANGELOG.md
- package.json
Reverts folio-org/ui-marc-authorities#278
> Revert "UIMARCAUTH-272: Upgrade the records-editor.records interface."

- CHANGELOG.md
- package.json
Added missing permission for editing MARC Authority records.
[UIMARCAUTH-273](https://issues.folio.org/browse/UIMARCAUTH-273)
> UIMARCAUTH-273 Added missing permission for editing MARC Authority records.

- CHANGELOG.md
- src/views/AuthoritiesSearch/ReportsModal/ReportsModal.js
Fix for "Month" dropdown is Not displayed in date picker element opened in modal window
[UIMARCAUTH-269](https://issues.folio.org/browse/UIMARCAUTH-269)
> UIMARCAUTH-269 "Month" dropdown is Not displayed in date picker element opened in modal window

- src/routes/BrowseRoute/BrowseRoute.js
- src/routes/BrowseRoute/BrowseRoute.test.js
- src/views/AuthoritiesSearch/AuthoritiesSearch.js
The focus should always be on the first result after clicking the previous/next button.
[UIMARCAUTH-275](https://issues.folio.org/browse/UIMARCAUTH-275)
[stripes-authority-components/pull/79](https://github.com/folio-org/stripes-authority-components/pull/79)
[ui-plugin-find-authority/pull/63](https://github.com/folio-org/ui-plugin-find-authority/pull/63)
https://user-images.githubusercontent.com/77053927/236485736-321635c5-997d-40d6-85b9-093c083f674c.mp4
> UIMARCAUTH-275: Fix the focus of the first result for the Browse search

- CHANGELOG.md
- package.json
Change records-editor.records interface name and permission names to marc-records-editor also from 4 to 5 version of interface
[UIMARCAUTH-286](https://issues.folio.org/browse/UIMARCAUTH-286)
> UIMARCAUTH-286 Change records-editor.records interface name and version 

- CHANGELOG.md
- package.json
- translations/ui-marc-authorities/en.json
New permission: MARC authority: Create MARC authority record
[UIMARCAUTH-289](https://issues.folio.org/browse/UIMARCAUTH-289)
> UIMARCAUTH-289 New permission: MARC authority: Create MARC authority record

- CHANGELOG.md
- package.json
Fix by adding new permission for get mapping-rules for highlight heading on marc view
> UIMARCAUTH-291 fix

- CHANGELOG.md
- mocks/authorities.json
- src/views/AuthoritiesSearch/AuthoritiesSearch.css
- src/views/AuthoritiesSearch/AuthoritiesSearch.js
- src/views/AuthoritiesSearch/AuthoritiesSearch.test.js
[UIMARCAUTH-298](https://issues.folio.org/browse/UIMARCAUTH-298)
https://github.com/folio-org/stripes-authority-components/pull/97
https://github.com/folio-org/ui-plugin-find-authority/pull/73
> UIMARCAUTH-298 Add Shared icon to MARC authority search results

- CHANGELOG.md
- src/routes/AuthorityViewRoute/AuthorityViewRoute.js
- src/routes/AuthorityViewRoute/AuthorityViewRoute.test.js
- src/views/AuthorityView/AuthorityView.js
- test/jest/__mock__/stripesCore.mock.js
Change tenant id to central when opening details of Shared Authority
https://github.com/folio-org/ui-marc-authorities/assets/19309423/27ac5297-047d-4dca-abec-63679201f8bf
[UIMARCAUTH-305](https://issues.folio.org/browse/UIMARCAUTH-305)
https://github.com/folio-org/ui-plugin-find-authority/pull/74
https://github.com/folio-org/stripes-authority-components/pull/99
https://github.com/folio-org/ui-quick-marc/pull/580
> UIMARCAUTH-305 Change tenant id to central when opening details of Shared Authority

- CHANGELOG.md
- src/routes/BrowseRoute/BrowseRoute.js
- src/routes/BrowseRoute/BrowseRoute.test.js
- src/views/AuthoritiesSearch/AuthoritiesSearch.js
Don't clear previous Search/Browse results to highlight the edited record.
Keeping previous results fixes the current issue, but occasionally leads to incorrect row focus in the `Browse` search after clicking the pagination buttons (when the previous page has fewer results than the next one) ([UIPFAUTH-51](https://issues.folio.org/browse/UIPFAUTH-51)) 
The newly added `pagingOffset` prop in the `stripes-components` allows always focus on the first row after pagination buttons are clicked.
[UIMARCAUTH-297](https://issues.folio.org/browse/UIMARCAUTH-297)
https://github.com/folio-org/ui-plugin-find-authority/pull/78
https://github.com/folio-org/stripes-authority-components/pull/110
https://github.com/folio-org/ui-plugin-find-authority/assets/77053927/7a7cc127-434c-48b3-ba69-67d06402e27d
> UIMARCAUTH-297: Don't clear previous Search/Browse results to highlight the edited record.

- CHANGELOG.md
- src/constants/queryKeys.js
- src/routes/AuthorityViewRoute/AuthorityViewRoute.js
- src/views/AuthoritiesSearch/AuthoritiesSearch.js
- src/views/AuthoritiesSearch/AuthoritiesSearch.test.js
Add a new column called `Authority source` for the browse and search results.
[UIMARCAUTH-343](https://issues.folio.org/browse/UIMARCAUTH-343)
https://github.com/folio-org/ui-plugin-find-authority/pull/86
https://github.com/folio-org/stripes-authority-components/pull/126
https://github.com/folio-org/ui-plugin-find-authority/assets/77053927/bff2f1fc-c3db-4f80-b907-2ca0effa6978
> UIMARCAUTH-343: Add new column called Authority source for the browse and search results.

- CHANGELOG.md
- src/views/AuthoritiesSearch/AuthoritiesSearch.js
ECS | "Authority record not found" error appears when only one record is returned to the result list after applied facet.
Issue was caused by previous open record data present which triggered fetch of a new MARC record with previous record's tenant.
Clear selected authority record data before opening another one.
https://github.com/folio-org/ui-marc-authorities/assets/19309423/e7716b7b-f2c2-4818-b551-632cfa88f94b
[UIMARCAUTH-351](https://issues.folio.org/browse/UIMARCAUTH-351)
> UIMARCAUTH-351 Clear selected authority record data before opening another one.

- CHANGELOG.md
- package.json
- src/views/AuthoritiesSearch/AuthoritiesSearch.js
Show  permissions for creating new authority record via UI (Q release)
[UIMARCAUTH-336](https://issues.folio.org/browse/UIMARCAUTH-336)
> UIMARCAUTH-336 Show  permissions for creating new authority record via UI (Q release)

- CHANGELOG.md
- src/routes/BrowseRoute/BrowseRoute.js
- src/views/AuthoritiesSearch/AuthoritiesSearch.js
Fix Facet counts changing when going Next or Prev page in Browse
Use first page query to fetch Browse facets
https://github.com/folio-org/ui-marc-authorities/assets/19309423/642eae73-ff96-49de-893b-52db1fe0064d
[UIMARCAUTH-353](https://issues.folio.org/browse/UIMARCAUTH-353)
https://github.com/folio-org/ui-plugin-find-authority/pull/88
https://github.com/folio-org/stripes-authority-components/pull/130
> UIMARCAUTH-353 Use first page Browse query for facet requests

- CHANGELOG.md
- src/views/AuthoritiesSearch/AuthoritiesSearch.js
Counter values and options for "Authority source", "Thesaurus" facet options do not change when changing search parameters
Need to send request to facets with current search query parameters
https://github.com/folio-org/ui-marc-authorities/assets/19309423/3f26c69f-ae71-4fc6-ab4e-ea646cdd54f9
[UIMARCAUTH-363](https://issues.folio.org/browse/UIMARCAUTH-363)
https://github.com/folio-org/stripes-authority-components/pull/136
> UIMARCAUTH-363 Counter values and options for Authority source, Thesaurus facet options do not change when changing search parameters

- package.json
- src/settings/ManageAuthoritySourceFiles/ManageAuthoritySourceFiles.js
- src/settings/ManageAuthoritySourceFiles/getValidators.js
- translations/ui-marc-authorities/en.json
- Added missing permission to get users from metadata
- Added validation for length of prefix field
- Fix issue with `active` field not being saved
[UIMARCAUTH-360](https://issues.folio.org/browse/UIMARCAUTH-360)
> UIMARCAUTH-360 Fix issues creating Authority Source files (follow-up)

- CHANGELOG.md
- src/routes/AuthorityQuickMarcRoute/AuthorityQuickMarcRoute.js
New `onSave` prop for quickMARC is added to handle saving and closing records without save separately
[UIMARCAUTH-374](https://issues.folio.org/browse/UIMARCAUTH-374)
https://github.com/folio-org/ui-quick-marc/pull/648
> UIMARCAUTH-374 Use `onSave` prop for quickMARC to handle saving records separately

- CHANGELOG.md
- src/commands.js
- src/constants/createAuthorityRoute.js
- src/constants/index.js
- src/views/AuthoritiesSearch/AuthoritiesSearch.js
- src/views/AuthoritiesSearch/AuthoritiesSearch.test.js
- MARC authority app - should have the `alt + n` keyboard shortcut for creating a new MARC authority record;
- MARC authority keyboard shortcut modal list - display the new shortcut key as the first row above the Edit a record shortcut key.
[UIMARCAUTH-369](https://issues.folio.org/browse/UIMARCAUTH-369)
> UIMARCAUTH-369: Add Create a new MARC authority record keyboard shortcut.

- CHANGELOG.md
- src/queries/useAuthoritiesDelete/useAuthorityDelete.js
- src/queries/useAuthoritiesDelete/useAuthorityDelete.test.js
- src/settings/ManageAuthoritySourceFiles/ManageAuthoritySourceFiles.css
- src/settings/ManageAuthoritySourceFiles/ManageAuthoritySourceFiles.js
- src/settings/ManageAuthoritySourceFiles/ManageAuthoritySourceFiles.test.js
- src/settings/ManageAuthoritySourceFiles/constants.js
- src/settings/ManageAuthoritySourceFiles/getFieldComponents.js
- src/settings/ManageAuthoritySourceFiles/getFormatter.js
- src/settings/ManageAuthoritySourceFiles/getValidators.js
- src/settings/ManageAuthoritySourceFiles/getValidators.test.js
- src/settings/ManageAuthoritySourceFiles/useManageAuthoritySourceFiles.js
- src/settings/ManageAuthoritySourceFiles/useManageAuthoritySourceFiles.test.js
- src/views/AuthorityView/AuthorityView.test.js
- test/jest/__mock__/stripesAuthorityComponents.mock.js
- test/jest/__mock__/stripesCore.mock.js
- translations/ui-marc-authorities/en.json
Updated imlementation of Manage Authority Source Files settings:
- now using `<EditableList>` instead of `<ControlledVocab>` because `<ControlledVocab>` uses `POST` method for updating records, but our API provides only `PATCH`
- separate presentation and logic into a view component and a hook
- updated tests
https://github.com/folio-org/ui-marc-authorities/assets/19309423/4a35cf8a-df78-4abb-abe9-4b12a364bce7
[UIMARCAUTH-359](https://issues.folio.org/browse/UIMARCAUTH-359)
https://github.com/folio-org/stripes-smart-components/pull/1435
https://github.com/folio-org/stripes-authority-components/pull/137
> UIMARCAUTH-359 Changed implementation for basic creating/updating logic

- CHANGELOG.md
- package.json
- src/settings/ManageAuthoritySourceFiles/ManageAuthoritySourceFiles.js
- src/settings/ManageAuthoritySourceFiles/ManageAuthoritySourceFiles.test.js
- test/jest/__mock__/stripesCore.mock.js
- translations/ui-marc-authorities/en.json
Handle deletion of Authority Source files
https://github.com/folio-org/ui-marc-authorities/assets/19309423/84e25775-cc9c-4476-9bd4-994a06d4f40e
[UIMARCAUTH-361](https://folio-org.atlassian.net/browse/UIMARCAUTH-361)
https://github.com/folio-org/stripes-smart-components/pull/1440
> UIMARCAUTH-361: DELETE | Create new settings options for configuring authority files

- src/routes/BrowseRoute/BrowseRoute.js
- src/routes/BrowseRoute/BrowseRoute.test.js
- src/routes/SearchRoute/SearchRoute.js
- src/routes/SearchRoute/SearchRoute.test.js
Show default html title when search query is empty
[UIMARCAUTH-371](https://folio-org.atlassian.net/browse/UIMARCAUTH-371)
> UIMARCAUTH-371 Show default html title when search query is empty (follow-up)

- CHANGELOG.md
- src/settings/ManageAuthoritySourceFiles/useManageAuthoritySourceFiles.js
- src/settings/ManageAuthoritySourceFiles/useManageAuthoritySourceFiles.test.js
PATCH endpoint changed to use `code` instead of `codes` property
[UIMARCAUTH-392](https://folio-org.atlassian.net/browse/UIMARCAUTH-392)
> UIMARCAUTH-392 When updating Authority Source files, send `code` instead of `codes` property.

- CHANGELOG.md
- src/settings/ManageAuthoritySourceFiles/constants.js
BE updated the endpoint to accept `''` as empty baseUrl value, so we need to update our defaults as well
[UIMARCAUTH-391](https://folio-org.atlassian.net/browse/UIMARCAUTH-391)
> UIMARCAUTH-391 Source Files settings - Send empty string instead of null as empty baseUrl value.

- CHANGELOG.md
- src/routes/BrowseRoute/BrowseRoute.js
- src/routes/SearchRoute/SearchRoute.js
- src/views/AuthoritiesSearch/AuthoritiesSearch.js
Pass the record search error to the `SearchResultsList` component.
[UIMARCAUTH-415](https://folio-org.atlassian.net/browse/UIMARCAUTH-415)
> UIMARCAUTH-415: Pass the record search error to the `SearchResultsList` component.

- CHANGELOG.md
- src/settings/ManageAuthoritySourceFiles/useManageAuthoritySourceFiles.js
Requests for Authority Source files should be made with current tenant id, because having only member tenant permissions is not enough to view the settings
[UIMARCAUTH-411](https://folio-org.atlassian.net/browse/UIMARCAUTH-411)
> UIMARCAUTH-411 Send requests for Source Files Settings with current tenant id.

- .github/workflows/build-npm-release.yml
- .github/workflows/build-npm.yml
- src/views/AuthoritiesSearch/AuthoritiesSearch.js
- src/views/AuthoritiesSearch/AuthoritiesSearch.test.js
Follow-up PR.
After adding the `showSortIndicator` property and extending the `nonInteractiveHeaders`, the Tab key navigating through the results list headers only works for interactive fields (not in the `nonInteractiveHeaders` list).
Revert `nonInteractiveHeaders` and use sortableColumns for MCL to be able to navigate through all result list headers and keep the sort indicator.
https://github.com/folio-org/stripes-authority-components/pull/166
[UIMARCAUTH-423](https://folio-org.atlassian.net/browse/UIMARCAUTH-423)
> UIMARCAUTH-423: Pass `sortableColumns` to the MCL and revert `onInteractiveHeaders` (follow-up).

- CHANGELOG.md
- package.json
_Copied from [https://github.com/folio-org/ui-marc-authorities/pull/415](https://github.com/folio-org/ui-marc-authorities/pull/415)_
[UIMARCAUTH-429](https://folio-org.atlassian.net/browse/UIMARCAUTH-429) Update SRS interface version and refactor SRS BE permissions
According to the epic [FOLIO-4044](https://folio-org.atlassian.net/browse/FOLIO-4044) some permissions have been changed in the `source-record-storage v3.3`
permission u`i-marc-authorities.authority-record.view `uses `source-storage.records.get`
Old permission | New permissions
-- | --
source-storage.records.get | source-storage.stream.marc-record-identifiers.collection.postsource-storage.records.collection.getsource-storage.records.item.getsource-storage.records.formatted.item.getsource-storage.stream.records.collection.get …
> UIMARCAUTH-429 Upgrade srs interface and be permission refactoring

- CHANGELOG.md
- src/views/AuthoritiesSearch/AuthoritiesSearch.js
- src/views/AuthorityView/AuthorityView.js
https://folio-org.atlassian.net/browse/UIMARCAUTH-422
Here we added a check for `ui-data-export permissions` to run a quick export
> UIMARCAUTH-422: Update required permissions for quick export of authority records

- CHANGELOG.md
- src/routes/AuthorityViewRoute/AuthorityViewRoute.js
- src/routes/AuthorityViewRoute/AuthorityViewRoute.test.js
Do not load MARC source until consortia data is available.
The issue was caused by a delay when loading consortia data. If an authority record is loaded before consortia data is available then we fetch MARC source from a member tenant, which is incorrect for shared records
https://github.com/user-attachments/assets/34b660bc-e76d-45c9-825c-d188300a3455
[UIMARCAUTH-438](https://folio-org.atlassian.net/browse/UIMARCAUTH-438)
> UIMARCAUTH-438 Do not load MARC source until consortia data is available.

- CHANGELOG.md
- package.json
- src/views/AuthorityView/AuthorityView.js
- src/views/AuthorityView/AuthorityView.test.js
- translations/ui-marc-authorities/en.json
Added a version history button that opens a version history pane
mod-audit endpoint for version history is not complete yet, so actual requests will be done in scope of a different story
https://github.com/user-attachments/assets/92bac149-129a-4b18-90a7-a1a0ab5c9d6c
[UIMARCAUTH-445](https://folio-org.atlassian.net/browse/UIMARCAUTH-445)
> UIMARCAUTH-445 MARC authority > View Source > Display Version History pane with an empty Version History component.

- CHANGELOG.md
- package.json
- src/constants/constants.js
- src/settings/MarcAuthoritySettings/MarcAuthoritySettings.js
- src/settings/MarcAuthoritySettings/MarcAuthoritySettings.test.js
- src/views/AuthorityView/AuthorityView.js
- src/views/AuthorityView/AuthorityView.test.js
Hide version history icon and settings if audit log feature is disabled.
[UIMARCAUTH-452](https://folio-org.atlassian.net/browse/UIMARCAUTH-452)
> UIMARCAUTH-452: Hide version history icon and settings if audit log feature is disabled.

- CHANGELOG.md
- src/views/AuthorityView/AuthorityView.js
Move focus on the detail view pane when record is opened automatically
https://github.com/user-attachments/assets/7b9044c9-72cd-4a94-90db-542c73a6fe6f
[UIMARCAUTH-477](https://folio-org.atlassian.net/browse/UIMARCAUTH-477)
> UIMARCAUTH-477 Move focus on the detail view pane when record is opened automatically

- src/views/AuthorityView/AuthorityView.js
Need to wait for central tenant permissions to load because it is also a condition to show loading pane. Focusing before permissions are loaded has no effect on the third pane.
[UIMARCAUTH-477](https://folio-org.atlassian.net/browse/UIMARCAUTH-477)
> UIMARCAUTH-477 wait for central tenant permissions to load before focusing third pane (follow-up)

- src/views/AuthoritiesSearch/AuthoritiesSearch.js
- src/views/AuthoritiesSearch/AuthoritiesSearch.test.js
A follow-up PR to hide "Save Authorities CQL query" button when in Browse.
[UIMARCAUTH-490](https://folio-org.atlassian.net/browse/UIMARCAUTH-490)
> UIMARCAUTH-490 hide "Save Authorities cql" button in Authorities Browse (follow-up)

- CHANGELOG.md
- src/views/AuthoritiesSearch/AuthoritiesSearch.js
- src/views/AuthoritiesSearch/AuthoritiesSearch.test.js
Do not show Save authorities UUIDs (CSV) option when user selects Browse toggle.
[UIMARCAUTH-497](https://folio-org.atlassian.net/browse/UIMARCAUTH-497)
> UIMARCAUTH-497 Do not show Save authorities UUIDs (CSV) option when user selects Browse toggle.

- src/components/AuthorityTitleManager/AuthorityTitleManager.js
- src/index.js
- src/views/AuthoritiesSearch/AuthoritiesSearch.js
`PropTypes.oneOfType` expects an array.
```
-  children: PropTypes.oneOfType(PropTypes.node, PropTypes.arrayOf(PropTypes.node)),
+  children: PropTypes.oneOfType([PropTypes.node, PropTypes.arrayOf(PropTypes.node)]),
```
> UIMARCAUTH-511 proptypes typo
